name: 'Terraform'

on:
  push:
    branches: [ "cloud-dev" ]
  pull_request:
    branches: [ "cloud-dev" ]

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash  
        working-directory: ./terraform

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup terraform 
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
        continue-on-error: true

      - name: Terraform Init
        run: terraform init

      - name: Terraform format
        run: terraform fmt -check
        # don't exit with error:
        continue-on-error: true

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -input=false

      # run only for push events
      - name: Terraform Apply
        if: github.event_name == 'push' && github.ref == 'refs/heads/cloud_dev'
        run: terraform apply -auto-approve -input=false

      